source = ~/.config/hypr/env.conf
exec-once = wlsunset -l 55.45 -L 37.37
exec-once = waybar & 
exec-once = wpaperd -d -c ~/.config/wpaperd/config.toml
exec-once = hypridle
exec-once = hyprlauncher -d
exec-once = systemctl --user start hyprpolkitagent

exec-once = [workspace 1 silent] $terminal
exec-once = [workspace special:magic silent] firefox

