source = ~/.config/hypr/env.conf
source = ~/.config/hypr/src/monitors.conf
source = ~/.config/hypr/src/autostart.conf
source = ~/.config/hypr/src/view.conf
source = ~/.config/hypr/src/input.conf
source = ~/.config/hypr/src/keybindings.conf
source = ~/.config/hypr/src/variables.conf
source = ~/.config/hypr/src/windows-workspaces.conf
source = ~/.config/hypr/src/master.conf
